import { customProvider } from "ai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import { createOpenAI } from "@ai-sdk/openai";
import type { ChatMode, SelectedModel } from "@/types/chat";
import { isAgentMode } from "@/lib/utils/mode-helpers";
import { openrouterAttributionHeaders } from "@/lib/ai/openrouter-attribution";
// import { withTracing } from "@posthog/ai";
// import PostHogClient from "@/app/posthog";
// import type { SubscriptionTier } from "@/types";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

const isXaiModelSlug = (value: unknown): boolean =>
  typeof value === "string" && value.toLowerCase().startsWith("x-ai/");

const requestCanRouteToXai = (body: unknown): boolean => {
  if (!isRecord(body)) return false;
  if (isXaiModelSlug(body.model)) return true;
  return Array.isArray(body.models) && body.models.some(isXaiModelSlug);
};

const hasOwnEncryptedContent = (value: unknown): boolean =>
  isRecord(value) && Object.hasOwn(value, "encrypted_content");

const stripEncryptedContent = (
  value: unknown,
  inReasoningDetails = false,
): { value: unknown; changed: boolean } => {
  if (Array.isArray(value)) {
    let changed = false;
    const cleaned: unknown[] = [];

    for (const item of value) {
      if (inReasoningDetails && hasOwnEncryptedContent(item)) {
        changed = true;
        continue;
      }
      const result = stripEncryptedContent(item, inReasoningDetails);
      changed ||= result.changed;
      cleaned.push(result.value);
    }

    return changed ? { value: cleaned, changed } : { value, changed: false };
  }

  if (!isRecord(value)) {
    return { value, changed: false };
  }

  let changed = false;
  const cleaned: Record<string, unknown> = {};

  for (const [key, entryValue] of Object.entries(value)) {
    if (inReasoningDetails && key === "encrypted_content") {
      changed = true;
      continue;
    }

    const nextInReasoningDetails =
      inReasoningDetails || key === "reasoning_details";
    const result = stripEncryptedContent(entryValue, nextInReasoningDetails);
    changed ||= result.changed;

    if (
      key === "reasoning_details" &&
      Array.isArray(result.value) &&
      result.value.length === 0
    ) {
      changed = true;
      continue;
    }

    cleaned[key] = result.value;
  }

  return changed ? { value: cleaned, changed } : { value, changed: false };
};

export const sanitizeOpenRouterRequestForXai = (
  body: unknown,
): { body: unknown; changed: boolean } => {
  if (
    !isRecord(body) ||
    !requestCanRouteToXai(body) ||
    !Array.isArray(body.messages)
  ) {
    return { body, changed: false };
  }

  let changed = false;
  const messages = body.messages.map((message) => {
    const result = stripEncryptedContent(message);
    changed ||= result.changed;
    return result.value;
  });

  if (!changed) return { body, changed: false };
  return { body: { ...body, messages }, changed: true };
};

const patchKimiReasoningToolCalls = (
  body: unknown,
): { body: unknown; changed: boolean } => {
  if (!isRecord(body)) return { body, changed: false };
  if (
    !Array.isArray(body.messages) ||
    !isRecord(body.reasoning) ||
    body.reasoning.enabled !== true
  ) {
    return { body, changed: false };
  }

  let changed = false;
  const messages = body.messages.map((message) => {
    if (
      isRecord(message) &&
      message.role === "assistant" &&
      Array.isArray(message.tool_calls) &&
      message.tool_calls.length > 0 &&
      !message.reasoning
    ) {
      changed = true;
      return { ...message, reasoning: "." };
    }
    return message;
  });

  return changed
    ? { body: { ...body, messages }, changed: true }
    : { body, changed: false };
};

const OPENROUTER_METADATA_HEADER = "X-OpenRouter-Experimental-Metadata";

const withOpenRouterMetadataHeader = (
  headers: HeadersInit | undefined,
): Headers => {
  const nextHeaders = new Headers(headers);
  if (!nextHeaders.has(OPENROUTER_METADATA_HEADER)) {
    nextHeaders.set(OPENROUTER_METADATA_HEADER, "enabled");
  }
  return nextHeaders;
};

// Custom fetch for OpenRouter provider-specific request-body repairs.
//
// - Kimi requires a `reasoning` field on assistant tool-call messages when
//   reasoning mode is enabled, but the AI SDK does not always include one.
// - xAI rejects encrypted reasoning blobs generated by a different provider
//   when OpenRouter falls back to Grok. The visible assistant text remains in
//   the prompt, so these provider-private blobs are safe to omit for xAI routes.
// - The metadata header opts into OpenRouter routing metadata for attribution.
const openrouterPatchFetch: typeof fetch = async (url, init) => {
  let nextInit: RequestInit = {
    ...init,
    headers: withOpenRouterMetadataHeader(init?.headers),
  };

  if (nextInit.body && typeof nextInit.body === "string") {
    try {
      const parsedBody = JSON.parse(nextInit.body) as unknown;
      const kimiPatched = patchKimiReasoningToolCalls(parsedBody);
      const xaiPatched = sanitizeOpenRouterRequestForXai(kimiPatched.body);
      if (kimiPatched.changed || xaiPatched.changed) {
        nextInit = { ...nextInit, body: JSON.stringify(xaiPatched.body) };
      }
    } catch {
      // If parsing fails, send the request as-is
    }
  }
  return globalThis.fetch(url, nextInit);
};

const openrouterBaseUrl = process.env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1";

const openrouter = createOpenRouter({
  fetch: openrouterPatchFetch,
  headers: openrouterAttributionHeaders,
});

const kiloGateway = createOpenAI({
  apiKey: process.env.OPENROUTER_API_KEY,
  baseURL: openrouterBaseUrl,
});

type OpenRouterInstance = typeof openrouter;

const isSelfHosted = process.env.SELF_HOSTED === "true";

const buildProviderMap = (or: OpenRouterInstance, gateway: ReturnType<typeof createOpenAI>) => {
  // Self-hosted: all models route through Kilo Gateway free models
  if (isSelfHosted) {
    const standard = gateway("kilo-auto/free");
    const pro = gateway("qwen/qwen3.7-plus:free");
    const max = gateway("nvidia/nemotron-3-super-120b-a12b:free");
    const auto = gateway("kilo-auto/free");
    return {
      "ask-model": auto,
      "ask-model-free": auto,
      "agent-model": auto,
      "agent-model-free": auto,
      "model-sonnet-4.6": pro,
      "model-gemini-3-flash": auto,
      "model-deepseek-v4-flash": auto,
      "model-opus-4.6": max,
      "model-kimi-k2.6": pro,
      "fallback-agent-model": auto,
      "fallback-ask-model": auto,
      "fallback-gemini-3.5-flash": auto,
      "fallback-grok-4.3": auto,
      "title-generator-model": standard,
    } as Record<string, any>;
  }

  return {
    "ask-model": or("google/gemini-3-flash-preview"),
    "ask-model-free": or("deepseek/deepseek-v4-flash"),
    "agent-model": gateway("gpt-4.1"),
    "agent-model-free": or("deepseek/deepseek-v4-flash"),
    "model-sonnet-4.6": or("anthropic/claude-sonnet-4-6"),
    "model-gemini-3-flash": or("google/gemini-3-flash-preview"),
    "model-deepseek-v4-flash": or("deepseek/deepseek-v4-flash"),
    "model-opus-4.6": or("anthropic/claude-opus-4-6"),
    "model-kimi-k2.6": or("moonshotai/kimi-k2.6:exacto"),
    "fallback-agent-model": or("google/gemini-3-flash-preview"),
    "fallback-ask-model": or("google/gemini-3-flash-preview"),
    "fallback-gemini-3.5-flash": or("google/gemini-3.5-flash"),
    "fallback-grok-4.3": or("x-ai/grok-4.3"),
    "title-generator-model": or("google/gemini-3-flash-preview"),
  } as Record<string, any>;
};

const baseProviders = buildProviderMap(openrouter, kiloGateway);

export type ModelName = keyof typeof baseProviders;

export const modelCutoffDates: Record<ModelName, string> &
  Record<string, string> = {
  "ask-model": isSelfHosted ? "May 2025" : "January 2025",
  "ask-model-free": "May 2025",
  "agent-model": isSelfHosted ? "May 2025" : "April 2024",
  "agent-model-free": "May 2025",
  "model-sonnet-4.6": "May 2025",
  "model-gemini-3-flash": "January 2025",
  "model-deepseek-v4-flash": "May 2025",
  "model-opus-4.6": "May 2025",
  "model-kimi-k2.6": "April 2024",
  "fallback-agent-model": "January 2025",
  "fallback-ask-model": "January 2025",
  "fallback-gemini-3.5-flash": "May 2026",
  "fallback-grok-4.3": "December 2025",
  "title-generator-model": "January 2025",
};

export const modelDisplayNames: Record<ModelName, string> &
  Record<string, string> = {
  "ask-model": "Auto — intelligent model router",
  "ask-model-free": "Auto — intelligent model router",
  "agent-model": "Auto — intelligent model router",
  "agent-model-free": "Auto — intelligent model router",
  "model-sonnet-4.6": isSelfHosted ? "Qwen 3.7 Plus (Free)" : "Anthropic Claude Sonnet 4.6",
  "model-gemini-3-flash": isSelfHosted ? "Kilo Auto Free" : "Google Gemini 3 Flash",
  "model-deepseek-v4-flash": "DeepSeek V4 Flash",
  "model-opus-4.6": isSelfHosted ? "Nemotron 3 Super (Free)" : "Anthropic Claude Opus 4.6",
  "model-kimi-k2.6": isSelfHosted ? "Qwen 3.7 Plus (Free)" : "Moonshot Kimi K2.6",
  "fallback-agent-model": "Auto — intelligent model router",
  "fallback-ask-model": "Auto — intelligent model router",
  "fallback-gemini-3.5-flash": isSelfHosted ? "Kilo Auto Free" : "Google Gemini 3.5 Flash",
  "fallback-grok-4.3": "Auto — intelligent model router",
  "title-generator-model": "DeepSeek V4 Flash",
};

export const getModelDisplayName = (modelName: ModelName): string => {
  return modelDisplayNames[modelName];
};

export const getModelCutoffDate = (modelName: ModelName): string => {
  return modelCutoffDates[modelName];
};

export function isAnthropicModel(modelName: string): boolean {
  return modelName.includes("sonnet") || modelName.includes("opus");
}

export function isDeepSeekModel(modelName: string): boolean {
  return (
    modelName === "ask-model-free" ||
    modelName === "agent-model-free" ||
    modelName === "model-deepseek-v4-flash"
  );
}

export function supportsMultimodalToolResults(modelName?: string): boolean {
  if (!modelName) return false;

  const normalized = modelName.toLowerCase();

  return (
    normalized === "ask-model" ||
    normalized.includes("gemini") ||
    normalized.includes("google/") ||
    isAnthropicModel(normalized) ||
    normalized.includes("anthropic/") ||
    normalized.includes("claude") ||
    normalized.includes("openai/") ||
    normalized.includes("gpt-") ||
    normalized.includes("o1") ||
    normalized.includes("o3") ||
    normalized.includes("o4") ||
    normalized.includes("x-ai/") ||
    normalized.includes("grok")
  );
}

export function isGeminiModel(modelName: string): boolean {
  return modelName === "ask-model" || modelName === "model-gemini-3-flash";
}

/**
 * Map a HackerAI tier id to the underlying provider key for a given mode.
 * Returns `null` for `"auto"` (the caller routes to the auto-router model
 * key instead). The Pro/Max tiers map to the same model in both modes; only
 * Lite differs (Gemini 3 Flash for ask, Kimi K2.6 for agent).
 */
export function resolveTierToProviderKey(
  tier: SelectedModel,
  mode: ChatMode,
): ModelName | null {
  if (tier === "auto") return null;
  if (isSelfHosted) {
    switch (tier) {
      case "hackerai-pro": return "model-sonnet-4.6";
      case "hackerai-max": return "model-opus-4.6";
      default: return "model-deepseek-v4-flash";
    }
  }
  switch (tier) {
    case "hackerai-standard":
      return isAgentMode(mode) ? "model-kimi-k2.6" : "model-gemini-3-flash";
    case "hackerai-pro":
      return "model-sonnet-4.6";
    case "hackerai-max":
      return "model-opus-4.6";
  }
}

export const myProvider = customProvider({
  languageModels: baseProviders,
});

export const createTrackedProvider = () =>
  // userId?: string,
  // conversationId?: string,
  // subscription?: SubscriptionTier,
  // phClient?: ReturnType<typeof PostHogClient> | null,
  {
    // PostHog provider tracking disabled
    // if (!phClient || subscription === "free") {
    //   return myProvider;
    // }
    //
    // const trackedModels: Record<string, any> = {};
    //
    // Object.entries(baseProviders).forEach(([modelName, model]) => {
    //   trackedModels[modelName] = withTracing(model, phClient, {
    //     ...(userId && { posthogDistinctId: userId }),
    //     posthogProperties: {
    //       modelType: modelName,
    //       ...(conversationId && { conversationId }),
    //       subscriptionTier: subscription,
    //     },
    //     posthogPrivacyMode: true,
    //   });
    // });
    //
    // return customProvider({
    //   languageModels: trackedModels,
    // });

    return myProvider;
  };
